/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function setLogListener(
  callback?: (...args: any[]) => any | undefined | null,
  minLevel?: string | undefined | null,
): void
export declare function generateMnemonic(): string
export interface MdkNodeOptions {
  network: string
  mdkApiKey: string
  vssUrl: string
  esploraUrl: string
  rgsUrl: string
  mnemonic: string
  lspNodeId: string
  lspAddress: string
}
export interface PaymentMetadata {
  bolt11: string
  paymentHash: string
  expiresAt: number
  scid: string
}
export interface ReceivedPayment {
  paymentHash: string
  amount: number
}
export interface NodeBalances {
  channelBalanceSats: number
  totalOnchainBalanceSats: number
  spendableOnchainBalanceSats: number
  totalAnchorChannelsReserveSats: number
  totalLightningBalanceSats: number
}
export interface NodeChannel {
  channelId: string
  counterpartyNodeId: string
  shortChannelId?: string
  inboundCapacityMsat: number
  outboundCapacityMsat: number
  isChannelReady: boolean
  isUsable: boolean
  isPublic: boolean
}
export declare class MdkNode {
  constructor(options: MdkNodeOptions)
  getNodeId(): string
  start(): void
  stop(): void
  syncWallets(): void
  getBalance(): NodeBalances
  listChannels(): Array<NodeChannel>
  receivePayment(minThresholdMs: number, quietThresholdMs: number): Array<ReceivedPayment>
  getInvoice(amount: number, description: string, expirySecs: number): PaymentMetadata
  getInvoiceWithScid(
    humanReadableScid: string,
    amount: number,
    description: string,
    expirySecs: number,
  ): PaymentMetadata
  getVariableAmountJitInvoice(description: string, expirySecs: number): PaymentMetadata
  getVariableAmountJitInvoiceWithScid(
    humanReadableScid: string,
    description: string,
    expirySecs: number,
  ): PaymentMetadata
  closeAllChannels(): void
  sendOnChain(address: string, amountSats: number): void
  payLnurl(lnurl: string, amountMsat: number, waitForPaymentSecs?: number | undefined | null): string
  payBolt11(bolt11Invoice: string): string
  payBolt12Offer(bolt12OfferString: string, amountMsat: number): string
}
