/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function generateMnemonic(): string
export interface MdkNodeOptions {
  network: string
  esploraUrl: string
  rgsUrl: string
  mnemonic: string
  lspNodeId: string
  lspAddress: string
}
export interface PaymentMetadata {
  bolt11: string
  paymentHash: string
  expiresAt: number
  scid: string
}
export interface ReceivedPayment {
  paymentHash: string
  amount: number
}
export declare class MdkNode {
  constructor(options: MdkNodeOptions)
  getNodeId(): string
  receivePayment(minThresholdMs: number, quietThresholdMs: number): Array<ReceivedPayment>
  getInvoice(amount: number, description: string, expirySecs: number): PaymentMetadata
  getInvoiceWithScid(
    humanReadableScid: string,
    amount: number,
    description: string,
    expirySecs: number,
  ): PaymentMetadata
  getVariableAmountJitInvoice(description: string, expirySecs: number): PaymentMetadata
  getVariableAmountJitInvoiceWithScid(
    humanReadableScid: string,
    description: string,
    expirySecs: number,
  ): PaymentMetadata
}
